"""Alembic 脚本模板 - 自动生成时的入口
修改 template 时只改这里
"""
"""initial_schema

Revision ID: bfad9ba1f6e3
Revises: 
Create Date: 2026-06-17 17:42:33.719301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfad9ba1f6e3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advice_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False, comment='用户ID'),
    sa.Column('index_code', sa.String(length=20), nullable=False, comment='指数代码'),
    sa.Column('trade_date', sa.DateTime(), nullable=False, comment='建议日期'),
    sa.Column('sentiment_score', sa.Float(), nullable=False, comment='情绪评分'),
    sa.Column('sentiment_label', sa.String(length=10), nullable=False, comment='情绪标签'),
    sa.Column('advice_type', sa.String(length=20), nullable=False, comment='建议类型: buy/hold/reduce/watch'),
    sa.Column('advice_content', sa.Text(), nullable=False, comment='建议内容'),
    sa.Column('suggested_position', sa.Float(), nullable=False, comment='建议仓位(%)'),
    sa.Column('is_executed', sa.Integer(), nullable=False, comment='是否执行: 0=否 1=是'),
    sa.Column('executed_at', sa.DateTime(), nullable=True, comment='执行时间'),
    sa.Column('execution_note', sa.String(length=500), nullable=False, comment='执行备注'),
    sa.Column('is_verified', sa.Integer(), nullable=False, comment='是否验证: 0=否 1=是'),
    sa.Column('actual_result', sa.Float(), nullable=False, comment='实际结果(%)'),
    sa.Column('accuracy_score', sa.Float(), nullable=False, comment='准确度评分'),
    sa.Column('signal_level', sa.String(length=2), nullable=True, comment='V5.0信号等级: S+/S/A/B/C/D/E'),
    sa.Column('confidence_stars', sa.Integer(), nullable=True, comment='V5.0置信度星级: 1-4'),
    sa.Column('is_executed_at', sa.DateTime(), nullable=True, comment='V5.0执行时间(替代is_executed)'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('advice_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_advice_log_user_id'), ['user_id'], unique=False)

    op.create_table('backtest_result',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False, comment='关联方案ID'),
    sa.Column('index_code', sa.String(length=20), nullable=False, comment='指数代码'),
    sa.Column('start_date', sa.Date(), nullable=False, comment='开始日期'),
    sa.Column('end_date', sa.Date(), nullable=False, comment='结束日期'),
    sa.Column('total_return', sa.Float(), nullable=False, comment='总收益率(%)'),
    sa.Column('annual_return', sa.Float(), nullable=False, comment='年化收益率(%)'),
    sa.Column('max_drawdown', sa.Float(), nullable=False, comment='最大回撤(%)'),
    sa.Column('win_rate', sa.Float(), nullable=False, comment='胜率(%)'),
    sa.Column('sharpe_ratio', sa.Float(), nullable=True, comment='夏普比率'),
    sa.Column('excess_return', sa.Float(), nullable=True, comment='超额收益(%)'),
    sa.Column('total_trades', sa.Integer(), nullable=False, comment='总交易次数'),
    sa.Column('equity_curve', sa.Text(), nullable=False, comment='净值曲线(JSON)'),
    sa.Column('trades_json', sa.Text(), nullable=False, comment='交易记录(JSON)'),
    sa.Column('run_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('backtest_result', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backtest_result_strategy_id'), ['strategy_id'], unique=False)

    op.create_table('backtest_strategy',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False, comment='用户ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='方案名称'),
    sa.Column('params_json', sa.Text(), nullable=False, comment='回测参数(JSON字符串)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否激活'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('backtest_strategy', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backtest_strategy_user_id'), ['user_id'], unique=False)

    op.create_table('factor_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('index_code', sa.String(length=20), nullable=False, comment='指数代码'),
    sa.Column('factor_name', sa.String(length=20), nullable=False, comment='因子名称'),
    sa.Column('trade_date', sa.String(length=10), nullable=False, comment='交易日期'),
    sa.Column('raw_value', sa.Float(), nullable=False, comment='原始值'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('quantile_percentile', sa.Float(), nullable=True, comment='V5.0分位数标准化结果(0.0-1.0)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('index_code', 'factor_name', 'trade_date', name='uq_factor_history')
    )
    with op.batch_alter_table('factor_history', schema=None) as batch_op:
        batch_op.create_index('idx_factor_history_lookup', ['index_code', 'factor_name', 'trade_date'], unique=False)

    op.create_table('fund_basic',
    sa.Column('fund_code', sa.String(length=10), nullable=False, comment='基金代码'),
    sa.Column('fund_name', sa.String(length=100), nullable=False, comment='基金全称'),
    sa.Column('fund_short_name', sa.String(length=50), nullable=False, comment='基金简称'),
    sa.Column('fund_type', sa.String(length=20), nullable=False, comment='基金类型: 股票型/混合型/指数型/债券型/货币型'),
    sa.Column('manager', sa.String(length=50), nullable=False, comment='基金经理'),
    sa.Column('company', sa.String(length=100), nullable=False, comment='基金公司'),
    sa.Column('inception_date', sa.Date(), nullable=True, comment='成立日期'),
    sa.Column('nav', sa.Float(), nullable=False, comment='最新净值'),
    sa.Column('accumulated_nav', sa.Float(), nullable=False, comment='累计净值'),
    sa.Column('fund_size', sa.Float(), nullable=False, comment='基金规模（亿元）'),
    sa.Column('benchmark', sa.String(length=100), nullable=False, comment='业绩基准'),
    sa.Column('tracking_index', sa.String(length=20), nullable=False, comment='跟踪指数代码'),
    sa.Column('risk_level', sa.String(length=10), nullable=False, comment='风险等级: R1-R5'),
    sa.Column('description', sa.Text(), nullable=False, comment='基金简介'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fund_basic', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fund_basic_fund_code'), ['fund_code'], unique=True)

    op.create_table('fund_nav',
    sa.Column('fund_code', sa.String(length=10), nullable=False, comment='基金代码'),
    sa.Column('nav_date', sa.Date(), nullable=False, comment='净值日期'),
    sa.Column('nav', sa.Float(), nullable=False, comment='单位净值'),
    sa.Column('accumulated_nav', sa.Float(), nullable=False, comment='累计净值'),
    sa.Column('daily_return', sa.Float(), nullable=False, comment='日收益率(%)'),
    sa.Column('week_return', sa.Float(), nullable=False, comment='周收益率(%)'),
    sa.Column('month_return', sa.Float(), nullable=False, comment='月收益率(%)'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fund_nav', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fund_nav_fund_code'), ['fund_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_fund_nav_nav_date'), ['nav_date'], unique=False)

    op.create_table('market_sentiment',
    sa.Column('index_code', sa.String(length=20), nullable=False, comment='指数代码(Tushare格式): 000001.SH/000300.SH/399001.SZ/399006.SZ'),
    sa.Column('index_name', sa.String(length=50), nullable=False, comment='指数名称'),
    sa.Column('trade_date', sa.Date(), nullable=False, comment='交易日期'),
    sa.Column('record_time', sa.DateTime(), nullable=False, comment='记录时间'),
    sa.Column('volatility', sa.Float(), nullable=False, comment='波动率(%)'),
    sa.Column('turnover_ratio', sa.Float(), nullable=False, comment='换手率(%)'),
    sa.Column('adv_decline_ratio', sa.Float(), nullable=False, comment='涨跌家数比'),
    sa.Column('new_high_ratio', sa.Float(), nullable=False, comment='新高占比(%)'),
    sa.Column('margin_balance', sa.Float(), nullable=False, comment='融资余额(亿)'),
    sa.Column('short_balance', sa.Float(), nullable=False, comment='融券余额(亿)'),
    sa.Column('bond_spread', sa.Float(), nullable=False, comment='债券利差(%)'),
    sa.Column('rsi_value', sa.Float(), nullable=False, comment='RSI(14)'),
    sa.Column('score_volatility', sa.Float(), nullable=False),
    sa.Column('score_turnover', sa.Float(), nullable=False),
    sa.Column('score_adv_decline', sa.Float(), nullable=False),
    sa.Column('score_new_high', sa.Float(), nullable=False),
    sa.Column('score_margin', sa.Float(), nullable=False),
    sa.Column('score_bond_equity', sa.Float(), nullable=False),
    sa.Column('score_rsi', sa.Float(), nullable=False),
    sa.Column('composite_score', sa.Float(), nullable=False, comment='加权综合评分(0-100)'),
    sa.Column('sentiment_label', sa.String(length=10), nullable=False, comment='情绪标签: extreme_fear/fear/neutral/greed/extreme_greed'),
    sa.Column('divergence_index', sa.Float(), nullable=False, comment='指数分化度(0-100)'),
    sa.Column('trend_direction', sa.String(length=10), nullable=False, comment='趋势方向: up/down/stable'),
    sa.Column('trend_strength', sa.Float(), nullable=False, comment='趋势强度(0-100)'),
    sa.Column('top3_factors', sa.String(length=200), nullable=False, comment='Top3因子(JSON)'),
    sa.Column('conclusion', sa.Text(), nullable=False, comment='一句结论'),
    sa.Column('operation_advice', sa.Text(), nullable=False, comment='操作建议'),
    sa.Column('is_extreme', sa.Integer(), nullable=False, comment='是否极端: 0=否 1=是'),
    sa.Column('abnormal_signals', sa.String(length=500), nullable=False, comment='异常信号(JSON)'),
    sa.Column('signal_level', sa.String(length=2), nullable=True, comment='V5.0信号等级: S+/S/A/B/C/D/E'),
    sa.Column('confidence_stars', sa.Integer(), nullable=True, comment='V5.0置信度星级: 1-4'),
    sa.Column('confidence_detail', sa.Text(), nullable=True, comment='V5.0置信度明细(JSON)'),
    sa.Column('factor_std', sa.Float(), nullable=True, comment='V5.0因子得分标准差'),
    sa.Column('triggered_defenses', sa.Text(), nullable=True, comment='V5.0触发的防线(JSON数组)'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('market_sentiment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_market_sentiment_index_code'), ['index_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_sentiment_trade_date'), ['trade_date'], unique=False)

    op.create_table('position_execution',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False, comment='用户ID'),
    sa.Column('fund_code', sa.String(length=20), nullable=False, comment='基金代码'),
    sa.Column('execute_date', sa.Date(), nullable=False, comment='执行日期(Asia/Shanghai)'),
    sa.Column('from_position_pct', sa.Float(), nullable=False, comment='调整前仓位%'),
    sa.Column('to_position_pct', sa.Float(), nullable=False, comment='调整后仓位%'),
    sa.Column('amount', sa.Float(), nullable=True, comment='调整金额(可选)'),
    sa.Column('signal_level', sa.String(length=2), nullable=False, comment='执行时信号等级'),
    sa.Column('confidence_stars', sa.Integer(), nullable=False, comment='执行时置信度星级'),
    sa.Column('reason', sa.Text(), nullable=False, comment='建议原因'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'fund_code', 'execute_date', name='uq_position_execution_daily')
    )
    with op.batch_alter_table('position_execution', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_position_execution_fund_code'), ['fund_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_position_execution_user_id'), ['user_id'], unique=False)

    op.create_table('user_portfolio',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False, comment='用户ID'),
    sa.Column('fund_code', sa.String(length=10), nullable=False, comment='基金代码'),
    sa.Column('fund_name', sa.String(length=100), nullable=False, comment='基金名称'),
    sa.Column('fund_type', sa.String(length=20), nullable=False, comment='基金类型'),
    sa.Column('holding_shares', sa.Float(), nullable=False, comment='持有份额'),
    sa.Column('cost_nav', sa.Float(), nullable=False, comment='成本净值'),
    sa.Column('current_nav', sa.Float(), nullable=False, comment='当前净值'),
    sa.Column('market_value', sa.Float(), nullable=False, comment='持仓市值'),
    sa.Column('total_return', sa.Float(), nullable=False, comment='累计收益'),
    sa.Column('return_rate', sa.Float(), nullable=False, comment='收益率(%)'),
    sa.Column('daily_return', sa.Float(), nullable=False, comment='日收益'),
    sa.Column('buy_date', sa.Date(), nullable=True, comment='买入日期'),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('portfolio_tag', sa.String(length=20), nullable=False, comment='组合标签: core/satellite/trading'),
    sa.Column('weight_pct', sa.Float(), nullable=False, comment='组合内权重(%)'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_portfolio', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_portfolio_fund_code'), ['fund_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_portfolio_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_portfolio', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_portfolio_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_portfolio_fund_code'))

    op.drop_table('user_portfolio')
    with op.batch_alter_table('position_execution', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_position_execution_user_id'))
        batch_op.drop_index(batch_op.f('ix_position_execution_fund_code'))

    op.drop_table('position_execution')
    with op.batch_alter_table('market_sentiment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_sentiment_trade_date'))
        batch_op.drop_index(batch_op.f('ix_market_sentiment_index_code'))

    op.drop_table('market_sentiment')
    with op.batch_alter_table('fund_nav', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fund_nav_nav_date'))
        batch_op.drop_index(batch_op.f('ix_fund_nav_fund_code'))

    op.drop_table('fund_nav')
    with op.batch_alter_table('fund_basic', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fund_basic_fund_code'))

    op.drop_table('fund_basic')
    with op.batch_alter_table('factor_history', schema=None) as batch_op:
        batch_op.drop_index('idx_factor_history_lookup')

    op.drop_table('factor_history')
    with op.batch_alter_table('backtest_strategy', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backtest_strategy_user_id'))

    op.drop_table('backtest_strategy')
    with op.batch_alter_table('backtest_result', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backtest_result_strategy_id'))

    op.drop_table('backtest_result')
    with op.batch_alter_table('advice_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_advice_log_user_id'))

    op.drop_table('advice_log')
    # ### end Alembic commands ###
